#! /bin/bash
echo "> Running integration test"
MAKE_JOB_NAME=${2}
MAKE_K8S_NAMESPACE=${1}
MAKE_TEST_YAML=${3}
MAKE_LOG_FILTER=INFO

# Create test/producer Job; Generates pod
echo "> Generating test job via yaml '${MAKE_TEST_YAML}'"
kubectl -n ${MAKE_K8S_NAMESPACE} apply -f ${MAKE_TEST_YAML}

# Get name of Pod generated by job creation
MAKE_POD_NAME=$(kubectl -n ${MAKE_K8S_NAMESPACE} get pods -o name | grep ${MAKE_JOB_NAME})
# Wait for pod to be ready
echo "> Waiting for pod '${MAKE_POD_NAME}' to be ready"
kubectl -n ${MAKE_K8S_NAMESPACE} wait --timeout=-1s --for=condition=Ready ${MAKE_POD_NAME} >/dev/null
# Follow logs from the pod
echo "> Following logs from pod '${MAKE_POD_NAME}'"
kubectl -n ${MAKE_K8S_NAMESPACE} logs ${MAKE_POD_NAME} -f | grep -v "${MAKE_LOG_FILTER}"
