version: "3.7"

services:
  kafka:
    image: singe/se_kafka
    build:
      context: .
      dockerfile: kafka/Dockerfile
  integration_test:
    image: singe/integration_test
    build:
      context: integration_test